### USER REGISTRATION API ###
POST http://localhost:8080/user/sign-up
Content-Type: application/json

{
    "email": "luca.bracchi5@studio.unibo.it",
    "password": "test123",
    "name": "luca"
}

### USER LOGIN API ###
POST http://localhost:8080/user/login
Content-Type: application/json

{
    "email": "luca.bracchi5@studio.unibo.it",
    "password": "test123"
}

### USER INFO API ###
GET http://localhost:8080/user/current
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJQYXJraW5nIENsaWVudCIsImV4cCI6MTY3NzE3NzMzOCwiZW1haWwiOiJsdWNhLmJyYWNjaGk1QHN0dWRpby51bmliby5pdCJ9.1gd9IJUf-O50BGnNKLAlfqY6Bi00OAMLNt8In8a41iQ

### DELETE ACCOUNT API ###
DELETE http://localhost:8080/user/current
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJQYXJraW5nIENsaWVudCIsImV4cCI6MTY3NzE3NzMzOCwiZW1haWwiOiJsdWNhLmJyYWNjaGk1QHN0dWRpby51bmliby5pdCJ9.1gd9IJUf-O50BGnNKLAlfqY6Bi00OAMLNt8In8a41iQ

### USER MAIL RECOVERY API ###
POST http://localhost:8080/user/recover-password
Content-Type: application/json

{
    "email": "luca.bracchi3@studio.unibo.it"
}

### CHANGE PASSWORD API ###
# called without oldPassword, required for password recovery flow 
POST http://localhost:8080/user/change-password
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJQYXJraW5nIENsaWVudCIsImlzcyI6Imx1Y2EgYnJhY2NoaSIsImV4cCI6MTY3NjIwNTEwMiwiZW1haWwiOiJsdWNhLmJyYWNjaGlAdGVzdC5pdCJ9.CmSr6GLEPV6empeIDTS_Ku2JFAzCXyN9eadktMqoaeE

{
    "oldPassword": "test123",
    "newPassword": "123test"
}

### test parking-slot api
PUT http://localhost:8080/parking-slot/occupy
Content-Type: application/json

{
    "slotId": 123,
    "endStop": 123
}