name: Build-Test

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:      
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Gradle build
        run: |
          ./gradlew clean build
