name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    tags: [ deployment ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew clean build
      
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})
      
    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run : docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" docker.io
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_HUB_USER}}/${{secrets.repo_name}}:${{steps.vars.outputs.tag}}
      
    - name: Publish dockerimage to docker hub
      run: docker push ${{secrets.DOCKER_HUB_USER}}/${{secrets.repo_name}}:${{steps.vars.outputs.tag}}
      
    - name: Build Docker image with latest tag
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_HUB_USER}}/${{secrets.repo_name}}:latest
      
    - name: Publish dockerimage to docker hub
      run: docker push ${{secrets.DOCKER_HUB_USER}}/${{secrets.repo_name}}:latest
